[package]
name = "csvexam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

csv = "1.1"

# chrono - crates.io: Rust Package Registry https://crates.io/crates/chrono
chrono = "0.4"